package com.example.hellotestrobobar;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class HelloTestRobobarTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void onexRobwine() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.00"));
    }

    @Test
    public void twoxRobaColaCheckout() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".btn-success"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".btn-success")).click();
    }

    @Test
    public void onexRobaCola1xRoboBeer() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€3.25"));
    }

    @Test
    public void onexRobaCola1xRoboBeer1xRobwine() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.25"));
    }

    @Test
    public void onexRoboBeer() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.00"));
    }

    @Test
    public void onexRoboBeerCheckoutLess18() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.id("ageInput")).click();
        driver.findElement(By.id("ageInput")).sendKeys("17");
        driver.findElement(By.cssSelector(".btn-success")).click();
        assertThat(driver.findElement(By.cssSelector(".alert > .ng-binding")).getText(), is("Only adults can buy alcohol!"));
    }

    @Test
    public void onexRoboBeerCheckoutGreater18() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.id("ageInput")).click();
        driver.findElement(By.id("ageInput")).sendKeys("21");
        driver.findElement(By.cssSelector(".btn-success")).click();
    }

    @Test
    public void onexRoboCola() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€1.25"));
    }

    @Test
    public void twoxRobwine() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€6.00"));
    }

    @Test
    public void twoxRoboBeer() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€4.00"));
    }

    @Test
    public void twoxRoboCola() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1847, 935));
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
        assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > .ng-binding")).getText(), is("€2.50"));
    }
}
